version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "gradio.egg-info/requires.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r gradio.egg-info/requires.txt
            pip install selenium==4.0.0a6.post2
#      - browser-tools/install-chromedriver
      - run:
          command: |
            chromedriver --version
          name: Check chrome driver install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "gradio.egg-info/requires.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            mkdir screenshots
      - run:
          command: |
            . venv/bin/activate
            python3 -m unittest
      - store_artifacts:
          path: /home/circleci/project/test/tmp
          destination: screenshots
      - store_test_results:
          path: test-reports/
orbs:
  browser-tools: circleci/browser-tools@1.1.3
